enum ActionType {
  GET_POST_REQUEST = "GET_POST_REQUEST",
  GET_POST_SUCCESS = "GET_POST_SUCCESS",
  GET_POST_FAIL = "GET_POST_FAIL",
  GET_IMAGES = "GET_IMAGES",
  GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS",
  GET_IMAGES_FAIL = "GET_IMAGES_FAIL",
  DELETE_IMAGES = "DELETE_IMAGES",
  SEARCH_IMAGES = "SEARCH_IMAGES",
  CHECK_IMAGE = "CHECK_IMAGE",
  SORT_BY_TITLE = "SORT_BY_TITLE",
}

export default ActionType;
